name: Build SLASI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.5'

    - name: Build Linux
      run: GOOS=linux GOARCH=amd64 go build -o SLASI -ldflags "-X main.SU=${{ secrets.SU }} -X main.SS=${{ secrets.SS }}"
